### ISSUE TITLE
No documentation of library functions

### ISSUE THREAD

**Issue by MattBrauer** [sparkfun/Micro_OLED_Breakout#4]
Would be nice if the README contained the usage for the library functions. Or at least a link to some proper documentation,

**Comment by santaimpersonator** [comment]
@MattBrauer This is the GitHub repository for the breakout board hardware. For the Arduino library, please reference this repository: https://github.com/sparkfun/SparkFun_Micro_OLED_Arduino_Library

There is documentation to get users started with the library in the [hookup guide](https://learn.sparkfun.com/tutorials/micro-oled-breakout-hookup-guide#using-the-arduino-library) for this product (linked on the library repo and this repo). Additionally,  there is a full breakdown of all the available functions from the **SparkFun Micro OLED library** in the [hookup guide for the Qwiic Micro OLED](https://learn.sparkfun.com/tutorials/qwiic-micro-oled-hookup-guide#library-overview) (linked on the library reo).

I am closing this issue because there is already documentation provided for **SparkFun Micro OLED library**.
