### ISSUE TITLE
RP2040/Pico port?

### ISSUE THREAD

**Issue by beshrkayali** [sparkfun/Micro_OLED_Breakout#5]
Hi,

Just wondering if there are any plans to provide a port for the new rp2040 / raspberry pi pico?

**Comment by santaimpersonator** [comment]
Because this issue doesn't involve this hardware repo, I am transferring it to the Arduino library for this product. The RP2040 is supported in the Arduino IDE and therefore, the library doesn't need to be ported.

If you are asking us to port the Arduino library to the Pico SDK, that is outside the our scope support on this product. Additionally, if you intend to use the Pico SDK... you should have the skills/knowledge to port the library on your own.

If you are interested in the microPython implementation, you can refer to the example in [our hookup guide](https://learn.sparkfun.com/tutorials/rp2040-thing-plus-hookup-guide/micropython-examples).

I believe in all cases, this issue can be closed.
